server:
  port: 8082
  servlet:
    contextPath: /produx
spring:
  datasource:
    password: 'yourPassword'
    url : jdbc:mysql://localhost:3306/'yourSQLServer'?user='yourSqlServerUsername'
    driverClassName: com.mysql.cj.jdbc.Driver
